;;; majutsu-bookmark-test.el --- Tests for bookmark helpers  -*- lexical-binding: t; -*-

;; SPDX-License-Identifier: GPL-3.0-or-later

;;; Commentary:

;; Tests for bookmark parsing and transient argument behavior.

;;; Code:

(require 'ert)
(require 'cl-lib)
(require 'seq)
(require 'majutsu-bookmark)

(defun majutsu-bookmark-test--sections (&optional section)
  "Return SECTION and all descendants, defaulting to `magit-root-section'."
  (let ((section (or section magit-root-section)))
    (cons section
          (apply #'append
                 (mapcar #'majutsu-bookmark-test--sections
                         (oref section children))))))

(defun majutsu-bookmark-test--record (&rest fields)
  "Return one bookmark-list machine record from FIELDS."
  (concat (mapconcat (lambda (field) (or field ""))
                     fields
                     majutsu-bookmark--list-field-separator)
          majutsu-bookmark--list-record-separator))

(ert-deftest majutsu-bookmark-split-remote-ref/basic ()
  (should (equal (majutsu--bookmark-split-remote-ref "main@origin")
                 '("main" . "origin"))))

(ert-deftest majutsu-bookmark-split-remote-ref/last-at ()
  (should (equal (majutsu--bookmark-split-remote-ref "foo@bar@origin")
                 '("foo@bar" . "origin"))))

(ert-deftest majutsu-bookmark-split-remote-ref/no-remote ()
  (should (equal (majutsu--bookmark-split-remote-ref "main")
                 '("main" . nil))))

(ert-deftest majutsu-bookmark-section-map/remaps-visit-thing-to-edit ()
  (should (eq (lookup-key majutsu-bookmark-section-map
                          [remap majutsu-visit-thing])
              #'majutsu-edit-changeset)))

(ert-deftest majutsu-bookmark-get-bookmark-names/local-args ()
  (let (seen-args)
    (cl-letf (((symbol-function 'majutsu-jj-lines)
               (lambda (&rest args)
                 (setq seen-args (flatten-list args))
                 '("main" "feature"))))
      (should (equal (majutsu--get-bookmark-names 'local) '("main" "feature")))
      (should (equal (seq-take seen-args 3) '("bookmark" "list" "--quiet")))
      (should-not (member "--all-remotes" seen-args))
      (should-not (member "--tracked" seen-args))
      (should (member "-T" seen-args))
      (let ((template (cadr (member "-T" seen-args))))
        (should (string-match-p (regexp-quote "(!self.remote())") template))
        (should (string-match-p (regexp-quote "self.present()") template))
        (should (string-match-p (regexp-quote "\\n") template))))))

(ert-deftest majutsu-bookmark-get-bookmark-names/remote-args ()
  (let (seen-args)
    (cl-letf (((symbol-function 'majutsu-jj-lines)
               (lambda (&rest args)
                 (setq seen-args (flatten-list args))
                 '("main@origin" "dev@upstream"))))
      (should (equal (majutsu--get-bookmark-names 'remote) '("main@origin" "dev@upstream")))
      (should (member "--all-remotes" seen-args))
      (should (member "-T" seen-args))
      (let ((template (cadr (member "-T" seen-args))))
        (should (string-match-p (regexp-quote "self.remote()") template))
        (should (string-match-p (regexp-quote "self.present()") template))
        (should (string-match-p (regexp-quote "\"@\"") template))))))

(ert-deftest majutsu-bookmark-get-bookmark-names/remote-tracked-args ()
  (let (seen-args)
    (cl-letf (((symbol-function 'majutsu-jj-lines)
               (lambda (&rest args)
                 (setq seen-args (flatten-list args))
                 '("main@origin"))))
      (should (equal (majutsu--get-bookmark-names 'remote-tracked) '("main@origin")))
      (should (member "--tracked" seen-args))
      (let ((template (cadr (member "-T" seen-args))))
        (should (string-match-p (regexp-quote "self.tracked()") template))))))

(ert-deftest majutsu-bookmark-get-bookmark-names/remote-untracked-args ()
  (let (seen-args)
    (cl-letf (((symbol-function 'majutsu-jj-lines)
               (lambda (&rest args)
                 (setq seen-args (flatten-list args))
                 '("topic@origin"))))
      (should (equal (majutsu--get-bookmark-names 'remote-untracked) '("topic@origin")))
      (should (member "--all-remotes" seen-args))
      (let ((template (cadr (member "-T" seen-args))))
        (should (string-match-p (regexp-quote "(!self.tracked())") template))))))

(ert-deftest majutsu-bookmark-forget-name-candidates/include-local-and-remote-bases ()
  (cl-letf (((symbol-function 'majutsu--get-bookmark-names)
             (lambda (&optional scope)
               (pcase scope
                 ('local '("main" "local-only"))
                 ('remote '("main@origin" "remote-only@upstream"))
                 (_ nil)))))
    (should (equal (majutsu--bookmark-forget-name-candidates)
                   '("main" "local-only" "remote-only")))))

(ert-deftest majutsu-bookmark-track-name-candidates/uses-untracked-remote-bases ()
  (cl-letf (((symbol-function 'majutsu--get-bookmark-names)
             (lambda (&optional scope)
               (when (eq scope 'remote-untracked)
                 '("main@origin" "topic@upstream" "main@fork")))))
    (should (equal (majutsu--bookmark-track-name-candidates)
                   '("main" "topic")))))

(ert-deftest majutsu-bookmark-untrack-name-candidates/uses-tracked-remote-bases ()
  (cl-letf (((symbol-function 'majutsu--get-bookmark-names)
             (lambda (&optional scope)
               (when (eq scope 'remote-tracked)
                 '("main@origin" "topic@upstream")))))
    (should (equal (majutsu--bookmark-untrack-name-candidates)
                   '("main" "topic")))))

(ert-deftest majutsu-bookmark-completion-template/emits-line-delimiters ()
  (should (string-match-p (regexp-quote "\\n") majutsu-bookmark--completion-template)))

(ert-deftest majutsu-bookmark-list-template/uses-typed-commitref-fields ()
  (should-not (string-match-p "format_commit_ref" majutsu-bookmark--list-template))
  (should (string-match-p "self\.removed_targets().map" majutsu-bookmark--list-template))
  (should (string-match-p "self\.added_targets().map" majutsu-bookmark--list-template))
  (should (string-match-p "format_commit_summary_with_refs" majutsu-bookmark--list-template))
  (should (string-match-p (regexp-quote "label(\"bookmark\"")
                          majutsu-bookmark--list-template))
  (should (string-match-p (regexp-quote "label(\"conflict\"")
                          majutsu-bookmark--list-template))
  (should (string-match-p (regexp-quote "\\x1E") majutsu-bookmark--list-template))
  (should (string-match-p (regexp-quote "\\x1D") majutsu-bookmark--list-template)))

(ert-deftest majutsu-bookmark-parse-list-output/attaches-targets-and-remote-state ()
  (let* ((output (concat
                  (majutsu-bookmark-test--record
                   "ref" "dev" "" "" "t" "" "" "" "" "" "" "" "" "")
                  (majutsu-bookmark-test--record
                   "target" "dev" "" "" "b052a92d" "rymwrkkn b052a92d summary")
                  (majutsu-bookmark-test--record
                   "ref" "dev" "origin" "t" "t" "" "" "t" "" "" "2" "t" "10" "")
                  (majutsu-bookmark-test--record
                   "target" "dev" "origin" "" "4bb5dd3b"
                   "sxwtxlqt/1 4bb5dd3b (hidden) summary")))
         (entries (majutsu-bookmark--parse-list-output output)))
    (should (= (length entries) 2))
    (should (equal (mapcar #'majutsu-bookmark--entry-ref entries)
                   '("dev" "dev@origin")))
    (should (equal (plist-get (car (plist-get (car entries) :targets)) :summary)
                   "rymwrkkn b052a92d summary"))
    (should (plist-get (cadr entries) :tracked))
    (should (equal (plist-get (cadr entries) :ahead-count) 2))
    (should (equal (plist-get (cadr entries) :behind-count) 10))))

(ert-deftest majutsu-bookmark-wash-list/nests-tracked-remotes-under-local-bookmark ()
  (let* ((output (concat
                  (majutsu-bookmark-test--record
                   "ref" "dev" "" "" "t" "" "" "" "" "" "" "" "" "")
                  (majutsu-bookmark-test--record
                   "target" "dev" "" "" "b052a92d" "rymwrkkn b052a92d summary")
                  (majutsu-bookmark-test--record
                   "ref" "dev" "origin" "t" "t" "" "" "t" "" "" "2" "t" "" "")
                  (majutsu-bookmark-test--record
                   "target" "dev" "origin" "" "4bb5dd3b"
                   "sxwtxlqt/1 4bb5dd3b (hidden) summary"))))
    (with-temp-buffer
      (majutsu-bookmark-list-mode)
      (let ((inhibit-read-only t)
            (magit-section-inhibit-markers t))
        (magit-insert-section (bookmark-list)
          (insert output)
          (majutsu-bookmark--wash-list nil))
        (let* ((sections (majutsu-bookmark-test--sections))
               (dev (seq-find (lambda (section)
                                (and (eq (oref section type) 'jj-bookmark)
                                     (equal (oref section value) "dev")))
                              sections))
               (origin (and dev
                            (seq-find (lambda (section)
                                        (and (eq (oref section type) 'jj-bookmark)
                                             (equal (oref section value) "dev@origin")))
                                      (oref dev children)))))
          (should dev)
          (should origin)
          (should-not (seq-find (lambda (section)
                                  (and (eq (oref section type) 'jj-bookmark)
                                       (equal (oref section value) "@origin")))
                                sections))
          (should (string-match-p "^dev:" (buffer-string)))
          (should (string-match-p "^  @origin" (buffer-string))))))))

(ert-deftest majutsu-bookmark-wash-list/sectionizes-conflicted-targets ()
  (let* ((output (concat
                  (majutsu-bookmark-test--record
                   "ref" "topic" "" "" "t" "t" "" "" "2" "1" "" "" "" "")
                  (majutsu-bookmark-test--record
                   "target" "topic" "" "-" "old123" "old-target")
                  (majutsu-bookmark-test--record
                   "target" "topic" "" "+" "new123" "new-target"))))
    (with-temp-buffer
      (majutsu-bookmark-list-mode)
      (let ((inhibit-read-only t)
            (magit-section-inhibit-markers t))
        (magit-insert-section (bookmark-list)
          (insert output)
          (majutsu-bookmark--wash-list nil))
        (let* ((sections (majutsu-bookmark-test--sections))
               (bookmark-sections
                (seq-filter (lambda (section)
                              (eq (oref section type) 'jj-bookmark))
                            sections))
               (commit-sections
                (seq-filter (lambda (section)
                              (eq (oref section type) 'jj-commit))
                            sections)))
          (should (= (length bookmark-sections) 1))
          (should (= (length commit-sections) 2))
          (should (equal (oref (car bookmark-sections) value) "topic"))
          (should (equal (mapcar (lambda (section) (oref section value))
                                 commit-sections)
                         '("old123" "new123")))
          (should (string-match-p (regexp-quote "topic (conflicted):")
                                  (buffer-string)))
          (should-not (string-match-p (regexp-quote "topic (conflicted) (2)")
                                      (buffer-string)))
          (should (string-match-p (regexp-quote "  - old-target") (buffer-string)))
          (should (string-match-p (regexp-quote "  + new-target") (buffer-string)))
          (save-excursion
            (goto-char (point-min))
            (search-forward "  - old-target")
            (should-not (memq 'diff-removed
                              (ensure-list (get-text-property (+ (match-beginning 0) 2)
                                                              'font-lock-face))))
            (goto-char (point-min))
            (search-forward "  + new-target")
            (should-not (memq 'diff-added
                              (ensure-list (get-text-property (+ (match-beginning 0) 2)
                                                              'font-lock-face))))))))))

(ert-deftest majutsu-bookmark-list-refresh-buffer/uses-structured-template ()
  (let (seen-args)
    (with-temp-buffer
      (majutsu-bookmark-list-mode)
      (cl-letf (((symbol-function 'majutsu-jj-wash)
                 (lambda (_washer _keep &rest args)
                   (setq seen-args (flatten-list args)))))
        (majutsu-bookmark-list-refresh-buffer))
      (should (member "-T" seen-args))
      (should (equal (cadr (member "-T" seen-args))
                     majutsu-bookmark--list-template)))))

(ert-deftest majutsu-bookmark-candidate-data/aggregates-local-and-remote-state ()
  (let ((sep majutsu-bookmark--completion-field-separator))
    (cl-letf (((symbol-function 'majutsu-jj-lines)
               (lambda (&rest _args)
                 (list (concat "main" sep "" sep "" sep "t" sep "" sep "t")
                       (concat "main" sep "origin" sep "" sep "t" sep "t" sep "t")
                       (concat "feature" sep "fork" sep "t" sep "t" sep "" sep "")))))
      (let* ((payload (majutsu-bookmark-candidate-data '("main" "feature")))
             (entries (plist-get payload :entries))
             (main (gethash "main" entries))
             (feature (gethash "feature" entries)))
        (should (equal (plist-get payload :candidates) '("main" "feature")))
        (should (plist-get main :local))
        (should (plist-get main :synced))
        (should (equal (plist-get main :tracked-remotes) '("origin")))
        (should (plist-get feature :conflict))
        (should (equal (plist-get feature :untracked-remotes) '("fork")))))))

(ert-deftest majutsu-bookmark-advance/builds-default-args ()
  (let (called)
    (cl-letf (((symbol-function 'majutsu-run-jj)
               (lambda (&rest args)
                 (setq called args)
                 0)))
      (majutsu-bookmark-advance)
      (should (equal (seq-remove #'null (flatten-tree called))
                     '("bookmark" "advance"))))))

(ert-deftest majutsu-bookmark-advance-to/builds-target-args ()
  (let (called)
    (cl-letf (((symbol-function 'majutsu-run-jj)
               (lambda (&rest args)
                 (setq called args)
                 0)))
      (majutsu-bookmark-advance-to "@")
      (should (equal (seq-remove #'null (flatten-tree called))
                     '("bookmark" "advance" "-t" "@"))))))

(ert-deftest majutsu-read-bookmark-name/uses-name-history ()
  (let (seen-history seen-category)
    (cl-letf (((symbol-function 'majutsu-bookmark-candidate-data)
               (lambda (&optional _candidates _directory)
                 (list :candidates '("main" "feature")
                       :entries (make-hash-table :test #'equal))))
              ((symbol-function 'completing-read)
               (lambda (_prompt collection _predicate _require-match _initial hist _default)
                 (setq seen-history hist
                       seen-category (plist-get completion-extra-properties :category))
                 (should (equal collection '("main" "feature")))
                 "main")))
      (should (equal (majutsu-read-bookmark-name "Bookmark") "main"))
      (should (eq seen-history 'majutsu-bookmark-name-history))
      (should (eq seen-category 'majutsu-bookmark)))))

(ert-deftest majutsu-bookmark-at-point/uses-exact-bookmark ()
  (cl-letf (((symbol-function 'magit-section-value-if)
             (lambda (type)
               (and (eq type 'jj-bookmark) "main"))))
    (should (equal (majutsu-bookmark-at-point) "main"))))

(ert-deftest majutsu-read-bookmark-name/defaults-to-exact-bookmark-at-point ()
  (let (seen-default)
    (cl-letf (((symbol-function 'majutsu-bookmark-at-point)
               (lambda (&optional _bookmark-type) "main"))
              ((symbol-function 'majutsu-bookmark-candidate-data)
               (lambda (&optional _candidates _directory)
                 (list :candidates '("main")
                       :entries (make-hash-table :test #'equal))))
              ((symbol-function 'completing-read)
               (lambda (_prompt _collection _predicate _require-match _initial _hist default)
                 (setq seen-default default)
                 "main")))
      (should (equal (majutsu-read-bookmark-name "Bookmark") "main"))
      (should (equal seen-default "main")))))

(ert-deftest majutsu-read-bookmark-patterns/falls-back-to-revision-bookmark-patterns ()
  (let (seen-default)
    (cl-letf (((symbol-function 'majutsu-bookmark-at-point)
               (lambda (&optional _bookmark-type) nil))
              ((symbol-function 'majutsu--bookmark-patterns-for-revision-at-point)
               (lambda (&optional _bookmark-type) "main,feature"))
              ((symbol-function 'majutsu-bookmark-candidate-data)
               (lambda (&optional _candidates _directory)
                 (list :candidates '("main" "feature")
                       :entries (make-hash-table :test #'equal))))
              ((symbol-function 'completing-read-multiple)
               (lambda (_prompt _collection _predicate _require-match _initial _hist default)
                 (setq seen-default default)
                 '("main"))))
      (should (equal (majutsu-read-bookmark-patterns "Bookmarks") '("main")))
      (should (equal seen-default "main,feature")))))

(ert-deftest majutsu-read-bookmark-patterns/filters-empty-input-and-uses-history ()
  (let (seen-history seen-category)
    (cl-letf (((symbol-function 'majutsu-bookmark-candidate-data)
               (lambda (&optional _candidates _directory)
                 (list :candidates '("main" "feature")
                       :entries (make-hash-table :test #'equal))))
              ((symbol-function 'majutsu-bookmark-at-point)
               (lambda () "main"))
              ((symbol-function 'completing-read-multiple)
               (lambda (_prompt collection _predicate _require-match _initial hist _default)
                 (setq seen-history hist
                       seen-category (plist-get completion-extra-properties :category))
                 (should (equal collection '("main" "feature")))
                 '("main" "glob:\"feat*\""))))
      (should (equal (majutsu-read-bookmark-patterns "Bookmarks")
                     '("main" "glob:\"feat*\"")))
      (should (eq seen-history 'majutsu-bookmark-pattern-history))
      (should (eq seen-category 'majutsu-bookmark)))))

(ert-deftest majutsu-bookmark-create/builds-multiple-exact-name-args ()
  (let (called)
    (cl-letf (((symbol-function 'magit-section-value-if)
               (lambda (_type) "@"))
              ((symbol-function 'majutsu-run-jj)
               (lambda (&rest args)
                 (setq called args)
                 0)))
      (majutsu-bookmark-create '("main" "feature"))
      (should (equal (seq-remove #'null (flatten-tree called))
                     '("bookmark" "create" "main" "feature" "-r" "@"))))))

(ert-deftest majutsu-bookmark-advance-patterns/builds-name-args ()
  (let (called)
    (cl-letf (((symbol-function 'majutsu-run-jj)
               (lambda (&rest args)
                 (setq called args)
                 0)))
      (majutsu-bookmark-advance-patterns '("main" "glob:\"feat*\""))
      (should (equal (seq-remove #'null (flatten-tree called))
                     '("bookmark" "advance"
                       "main" "glob:\"feat*\""))))))

(ert-deftest majutsu-bookmark-set/builds-multiple-exact-name-args ()
  (let (called)
    (cl-letf (((symbol-function 'majutsu-run-jj)
               (lambda (&rest args)
                 (setq called args)
                 0)))
      (majutsu-bookmark-set '("main" "feature") "@")
      (should (equal (seq-remove #'null (flatten-tree called))
                     '("bookmark" "set" "main" "feature" "-r" "@"))))))

(ert-deftest majutsu-bookmark-track/reads-patterns-and-calls-jj ()
  (let (called)
    (cl-letf (((symbol-function 'majutsu-remote-candidate-data)
               (lambda (&optional _directory)
                 (list :candidates '("origin" "upstream")
                       :entries (make-hash-table :test #'equal))))
              ((symbol-function 'completing-read-multiple)
               (lambda (prompt _collection &rest _args)
                 (cond
                  ((string-match-p "Track bookmark name" prompt)
                   '("main" "glob:\"feat*\""))
                  ((string-match-p "Remote.*pattern" prompt)
                   '("origin" "upstream"))
                  (t nil))))
              ((symbol-function 'majutsu-run-jj)
               (lambda (&rest args)
                 (setq called args)
                 0))
              ((symbol-function 'message) (lambda (&rest _args) nil)))
      (majutsu-bookmark-track)
      (should (equal (seq-remove #'null (flatten-tree called))
                     '("bookmark" "track"
                       "main" "glob:\"feat*\""
                       "--remote" "origin"
                       "--remote" "upstream"))))))

(ert-deftest majutsu-bookmark-delete/builds-pattern-args ()
  (let (called)
    (cl-letf (((symbol-function 'majutsu-run-jj)
               (lambda (&rest args)
                 (setq called args)
                 0))
              ((symbol-function 'message) (lambda (&rest _args) nil)))
      (majutsu-bookmark-delete '("main" "glob:\"feat*\""))
      (should (equal (seq-remove #'null (flatten-tree called))
                     '("bookmark" "delete"
                       "main" "glob:\"feat*\""))))))

(ert-deftest majutsu-bookmark-forget/builds-pattern-args ()
  (let (called)
    (cl-letf (((symbol-function 'majutsu-run-jj)
               (lambda (&rest args)
                 (setq called args)
                 0))
              ((symbol-function 'message) (lambda (&rest _args) nil)))
      (majutsu-bookmark-forget '("main" "glob:\"feat*\""))
      (should (equal (seq-remove #'null (flatten-tree called))
                     '("bookmark" "forget"
                       "main" "glob:\"feat*\""))))))

(ert-deftest majutsu-bookmark-untrack/builds-remote-args ()
  (let (called)
    (cl-letf (((symbol-function 'majutsu-run-jj)
               (lambda (&rest args)
                 (setq called args)
                 0))
              ((symbol-function 'message) (lambda (&rest _args) nil)))
      (majutsu-bookmark-untrack '("main" "glob:\"ci/*\"") '("origin" "upstream"))
      (should (equal (seq-remove #'null (flatten-tree called))
                     '("bookmark" "untrack"
                       "main" "glob:\"ci/*\""
                       "--remote" "origin"
                       "--remote" "upstream"))))))

;;; majutsu-bookmark-test.el ends here
